### ISSUE TITLE
IDEAS FOR CELESTE

### ISSUE THREAD

**Issue by lunaisnotaboy** [lunaisnotaboy/celeste#1]
This is basically just a place for people to suggest and talk about ideas for Celeste. There's probably a better way to do this, but I'm too lazy.

**Comment by 23marabi** [comment]
:3

**Comment by lunaisnotaboy** [comment]
@nullndvoid it's a work in progress, nothing's implemented yet because our personal lives got in the way

if you're actually asking whether or not it will build, [then yes](https://github.com/lunaisnotaboy/celeste/blob/main/DEVELOPMENT.md), but there won't be anything there except a few test components

sorry to disappoint!

(p.s. we're hoping to start working on it again here soon, so look out for that!)
